# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GaQZNlfB_zf2vC1JSBeBOsyUA6LJwIY1
"""

f = open('/content/med.txt')
pas = []
good = 0
for i in f:
  a = i[0:-1]
  if len(i)==10:
    count = 0
    pas.append(i[0:-1])
    if a.isdigit()== False:
        count+=1
    if count !=0:
      good+=1
print(good,pas,sep = '\n')

